package Cipher.Algorithms.SHA256;

import java.util.Scanner;

public class SHA256Main {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("[AES-MAIN] : Enter a Message to whose HashCode need to be generated using SHA256 Algorithm");
        String userMessage = sc.nextLine();

        System.out.println("\n\n");
        System.out.print("[SHA256Main] : HashCode Generated By SHA-256 Algorithm for --> ");
        System.out.println(userMessage);
        System.out.println("[O/P]: "+SHA256.toHexString(SHA256.getSHA(userMessage)));
    }
}
